"""unique violation fingerprint per scan

Revision ID: d831999cc483
Revises: 7d1b71472011
Create Date: 2026-06-14 20:13:15.833908

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d831999cc483"
down_revision: Union[str, Sequence[str], None] = "7d1b71472011"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_violation_scan_fingerprint", "violations", ["scan_id", "fingerprint"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_violation_scan_fingerprint", "violations", type_="unique")
    # ### end Alembic commands ###
